# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Appium CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
  
    steps:
      - uses: actions/checkout@v3
      - name: Yarn Install
        run: |
          yarn install
        
      - name: Install React Native CLI
        run: |
          yarn add react-native-cli
          yarn add appium appium-doctor wd
      
      - name: Run Appium Doctor
        run: |
          ./node_modules/.bin/appium-doctor   

      - name: Pod Install
        run: |
          cd ios && pod install && cd ..

      - name: Use HTTPS repos
        run: |
          git config --global url."https://github".insteadOf ssh://git@github 

      - name: Start the Appium Server
        run: ./node_modules/.bin/appium --log-timestamp --log-no-colors --allow-insecure chromedriver_autodownload > appium.log &

      - name: Poll for Appium Server to Start
        run: |
          until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/wd/hub/sessions); do
            sleep 5
          done

      - name: Build application through xcode
        run:  cd ios && xcodebuild -workspace GithubActionsTest.xcworkspace -scheme GithubActionsTest -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' && cd ..

      - name: Open Metro Bundler in Background
        run: |
          yarn start > bundler.log &

      - name: Build iOS App and Run Tests
        env:
          E2E_TEST_PLATFORM: 'ios'
          E2E_TEST_DEFAULTS: 'true'
          E2E_TEST_TAGS: 'E2E'
          TEST_ENV: 'test'
        run: |
          npx react-native run-ios
          BUILT_APP=`find ~/Library/Developer/Xcode/DerivedData -name GithubActionsTest.app | grep Build/Products/Debug-iphonesimulator/GithubActionsTest.app`
          mkdir -p ios/build/GithubActionsTest/Build/Products/Debug-iphonesimulator
          cp -R $BUILT_APP ios/build/GithubActionsTest/Build/Products/Debug-iphonesimulator
          sleep 30
          yarn test 

      # Upload Bundler Logs
      - name: Upload Build logs
        uses: actions/upload-artifact@v1
        with:
          name: bundler.log
          path: bundler.log          
      # Upload Appium Logs
      - name: Upload Appium logs
        uses: actions/upload-artifact@v1
        with:
          name: appium.log
          path: appium.log
      # Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v1
        with:
          name: e2e-results
          path: __tests__